Fix persistent halt command
nasa-jpl/jsd pull request #102
Opened 2023-09-13 22:36 UTC by preston-rogers

This pull request is a follow up of the previous pull request for fix-persistent-halt-command.

This pull request solves the problem using a flag that ensures that the ELMO has time to switch to operation enabled before processing halt commands.

Thus far, this implementation is untested.

2023-09-13 22:40 UTC, preston-rogers commented
@d-loret Regarding this implementation, I am only concerned with what the value of "enabling_operation" would be at initialization of the state struct.
By default, I believe booleans are undefined by value. Would this be an issue?

2023-09-16 05:41 UTC, d-loret requested changes
This follows what I suggested but we need to turn off the flag when transitioning into the fault state. See also my comment on where we need to initialize the flag.
 I commented only in the EGD files, but the comments apply to the EPD files too.

2023-09-16 05:41 UTC, d-loret commented on src/jsd_egd_types.h
> +  bool                        enabling_operation;
Let's initialize the flag at the end of `jsd_egd_init` where we initialize other variables of the state.

2023-09-18 16:27 UTC, preston-rogers commented on src/jsd_egd_types.h
> +  bool                        enabling_operation;
Done

2023-09-18 16:27 UTC, preston-rogers commented on src/jsd_egd.c
> +      state->enabling_operation  = false;
So I'm guessing you determined that setting the new_reset to false when the platinum drive enters a fault state is correct (as per the TODO comment)?
I have just made these changes.

2023-09-18 16:27 UTC, preston-rogers commented on src/jsd_egd.c
> +  if (!state->enabling_operation) state->new_halt_command = false;
Done

2023-09-26 04:26 UTC, d-loret approved these changes
Looks good to me.
Please test on EGD before merging.

2023-09-28 00:48 UTC, merged