Dloret platinum sil optimized
nasa-jpl/jsd pull request #104
Opened 2023-09-21 05:29 UTC by d-loret

Added SIL mode to EPD driver. Number and type of user registers are configurable and PDO mapping is space-optimized automatically.

2023-09-25 23:30 UTC, alex-brinkman commented on src/jsd_epd_types.h
> +} jsd_epd_state_sil_t;
Don't you need to report out the SIL variables here?

e.g. 

```
  // Data specific to SIL mode
  int32_t sil_inputs_r1[JSD_EPD_SIL_R1_MAX_NUM];   ///< 0x22F3
  double  sil_inputs_r2[JSD_EPD_SIL_R2_MAX_NUM];   ///< 0x22F4
  int32_t sil_outputs_r1[JSD_EPD_SIL_R1_MAX_NUM];  ///< 0x22F3
  double  sil_outputs_r2[JSD_EPD_SIL_R2_MAX_NUM];  ///< 0x22F4
  ```

2023-09-25 23:46 UTC, alex-brinkman commented on src/jsd_epd.c
> +int jsd_epd_config_PDO_mapping(ecx_contextt* ecx_context, uint16_t slave_id,
This function is over 400 lines of code, can you break it down into smaller functions?

2023-09-26 00:11 UTC, alex-brinkman requested changes
Both the `epd_config_t` and `epd_state_t` contain unions which signal to me that there are 2 different drivers here masquerading as one. It is going to be a challenge to communicate how to use these two specialization to users. 

The broken up RxPDO struct means that the code is that much more susceptible to being broken accidentally in the future by maintainers. Better to have distinct, fixed RXPDO structs for typecasting void data rather than several of these packed structs strung together IMO.

The PDO mapping code is undecipherable to a maintainer - I found it difficult to review and would struggle to make any bugfixes or feature changes, esp. the PO2SO function. Consider refactoring that or adding in comments to describe how you're laying out the memory.

2023-09-26 19:43 UTC, d-loret commented on src/jsd_epd.c
> +int jsd_epd_config_PDO_mapping(ecx_contextt* ecx_context, uint16_t slave_id,
Yes, I'm actually going to add a utility function. I can add more comments to make clear what is going on.

2023-09-26 19:47 UTC, d-loret commented on src/jsd_epd_types.h
> +} jsd_epd_state_sil_t;
My answer is no because I do not want the user to have access to the raw arrays. The indexing from the Platinum point of view starts at 1, and I split the lower half in the registers R1 and R2 for inputs, and the second half for outputs.
I added getters and setters to interact with the SIL R1 and R2 variables. Hence, client code can call the `jsd_epd_get_state` first to retrieve the common data, and then the SIL R1/R2 getters to retrieve the output data associated to them.

2023-10-07 02:25 UTC, d-loret commented
Abandoned since the addition of the SIL driver was implemented in a different PR. Review comments were addressed there.

2023-10-07 02:25 UTC, closed without merging