Prestonr feature add wkc driver saves
nasa-jpl/jsd pull request #110
Opened 2024-07-31 01:52 UTC by preston-rogers

Added a function that can be called by fastcat to confirm if jsd devices are operational at time of bad working counter. This will allow one to differentiate between situations where the CPU is overloaded and if there is simply poor physical connections to a device. 

I have attached three pictures:
The first being where the entire JSD device is turned off (corresponds to poor power to the jsd bus). 
The second where a single device at the end of the bus was unplugged (corresponds to a single bad device connection).
The third being where the timeout for jsd_read was set to a very small number to force the underlying SOEM function to time out (corresponds to no faulty JSD connections).

![image](https://github.com/user-attachments/assets/d4ad4882-e465-4abf-b975-d0b5e6ef78f6)
![image](https://github.com/user-attachments/assets/41f13cc7-76b1-41d7-9db6-cb332d8241aa)

2024-08-02 16:00 UTC, alex-brinkman requested changes
Good work, this feature will definitely help diagnose and debug issues. checkout my review comments and feel free to reach out for more discussion

2024-08-05 17:52 UTC, preston-rogers commented on src/jsd.c
> +  ecx_receive_processdata(&self->ecx_context, EC_TIMEOUTRET, bad_wkc_indices);
Added the following function:
jsd_all_slaves_operational(jsd_t* self) that pretty much does what you suggest

2024-08-29 21:22 UTC, kwehage requested changes
See comments

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +  int slave;
Reduce the scope of `slave` here:
```
for(int slave=1, slave <= *self.->ecx_context.slavecount; slave++) {
   ...
}
```

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +      MSG("We experienced an ECAT error. When this occurs, error information aught to be saved. "
aught is not the correct word here. Who is "we"? Please update error message as:
"An ECAT error occurred; the error list is displayed below:"

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +          "Errors in error list displayed below:\n");
Do we need to add a line break here? doesnt this add an extra line of whitespace?

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +      while(self->ecx_context.ecaterror) MSG("%s\n", ecx_elist2string(&self->ecx_context));
This needs a timeout or counter to avoid the (unlikely) possibility of polling indefinitely.

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +      MSG("Went through all errors in the elist stack.\n");
If you call it an "error list" above, call it an "error list" here also. Is it a stack or a list?  Better to change to something like:
"Finished reporting errors in error list" or just remove this line altogether.

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +          (EC_STATE_SAFE_OP + EC_STATE_ERROR)) {
I wondered about this weird syntax, but I see it comes from SOEM, so all is good.

2024-08-29 21:22 UTC, kwehage commented on src/jsd.c
> +  int slave;
It's also weird that they're using a signed integer to refer to a count, but this comes from SOEM

2024-08-29 22:06 UTC, dwai-wai commented on src/jsd.c
> +          "Errors in error list displayed below:\n");
Correct, the `MSG` macro already adds a newline, so no need to add one manually

2024-08-29 22:06 UTC, dwai-wai commented on src/jsd.c
> +      while(self->ecx_context.ecaterror) MSG("%s\n", ecx_elist2string(&self->ecx_context));
Welp, I was running this with srl-gcat and I ended up with an infinite loop, I had to `ctrl+\` to exit.

And FWIW, my infinite loop was just spamming blank lines, (i.e `ecx_elist2string(&self->ecx_context) == ""`)

2024-08-29 22:13 UTC, dwai-wai commented on src/jsd.c
> +      while(self->ecx_context.ecaterror) MSG("%s\n", ecx_elist2string(&self->ecx_context));
Oh unpacking this some more `self->ecx_context.ecaterror` is a bool, so unless we are going to clear that error flag, this is meant to "block" the application, and not really a way to unfurl via `ecx_elist2string` all the possible errors in the error list. 
If there's only one error, we would just print it over and over. I am not sure if this is the intent/outcome we want

2024-08-29 23:59 UTC, preston-rogers commented on src/jsd.c
> +      MSG("Went through all errors in the elist stack.\n");
It's a list of errors implemented as a stack. I'll change the message, however

2024-08-30 00:00 UTC, preston-rogers commented on src/jsd.c
> +          (EC_STATE_SAFE_OP + EC_STATE_ERROR)) {
Yeah Dennis commented on this too. If they're both one-hot pieces of data, an addition does the same as a bitwise OR

2024-08-30 00:01 UTC, preston-rogers commented on src/jsd.c
> +      while(self->ecx_context.ecaterror) MSG("%s\n", ecx_elist2string(&self->ecx_context));
Actually this is a bug that Will and I found with SOEM. Even though the elist is empty, ecaterror still states there is an error. The ecaterror flag aught to be cleared once the list is emptied.
So @kwehage fear of an infinite loop is valid

2024-08-30 00:04 UTC, dwai-wai commented on src/jsd.c
> +      while(self->ecx_context.ecaterror) MSG("%s\n", ecx_elist2string(&self->ecx_context));
>  The ecaterror flag aught to be cleared once the list is emptied.

It's more low level, but do you want to consider this as the conditional?
https://github.com/nasa-jpl/jsd/pull/112/files#diff-ec8bc2dbf8b89c6e78c73f1adf5732f1dff61d11f7cf4f22dd01241cb7cb39e3R285

2024-08-30 00:12 UTC, preston-rogers commented on src/jsd.c
> +      while(self->ecx_context.ecaterror) MSG("%s\n", ecx_elist2string(&self->ecx_context));
@kwehage I just added a counter that once a certain max count is reached, it terminates the while loop

2024-08-30 00:13 UTC, preston-rogers commented on src/jsd.c
> +          "Errors in error list displayed below:\n");
Modified this

2024-08-30 00:13 UTC, preston-rogers commented on src/jsd.c
> +      MSG("We experienced an ECAT error. When this occurs, error information aught to be saved. "
Modified

2024-10-17 16:16 UTC, closed without merging