Adds driver for Micro-Epsilon ILD1900 sensor
nasa-jpl/jsd pull request #29
Opened 2022-07-07 06:11 UTC by d-loret

Summary:
Adds the JSD driver for the Micro-Epsilon optoNCDT ILD1900 laser
sensor which measures distance with high precision.

Test Plan:
Performed preliminary testing via the written test executable and
the terminal connected to a local EtherCAT network. No inputs were
connected yet.

Reviewers: alex-brinkman, kwehage

2022-07-21 17:42 UTC, alex-brinkman requested changes
Great Job Daniel, You did an excellent job documenting the code and respecting the intended private/public API exposure!

2022-07-21 17:42 UTC, alex-brinkman commented on src/jsd_ild1900.c
> +}
nice!

2022-07-21 17:42 UTC, alex-brinkman commented on src/jsd_ild1900_types.h
> +                               averaging_type;  ///< Type of averaging formula applied to measurements
nitpick: I find this whitespacing odd but it's immaterial to me

2022-07-21 17:42 UTC, alex-brinkman commented on src/jsd_ild1900_types.h
> +           unlinearized_center_of_gravity;  ///< Unlinearized distance in percentage
nit whitespacing

2022-07-21 17:42 UTC, alex-brinkman commented on src/jsd_ild1900_types.h
> +           counter;  ///< Measurement counter. Distinguishes separate measurements.
nit whitespacing

2022-07-21 17:42 UTC, alex-brinkman commented on src/jsd_ild1900.c
> +                    JSD_ILD1900_SMR_MAP[config->model];
![image](https://user-images.githubusercontent.com/76965622/180277642-07dbcf0c-6283-4651-8628-654fc78a3eb5.png)
I believe you are mixing units of mm with meters in this calc, please review.

2022-07-21 17:42 UTC, alex-brinkman commented on src/jsd_ild1900.c
> +   * ILD1900 sensors do not support Complete Access. Steps to set TxPDO
Sorry CA didn't pan out for this sensor, good job tracking that down!

2022-07-21 17:43 UTC, alex-brinkman commented on src/jsd_ild1900.c
> +}
I was referring to the powerof2() function

2022-07-30 00:40 UTC, d-loret commented on src/jsd_ild1900_types.h
> +                               averaging_type;  ///< Type of averaging formula applied to measurements
It's git clang-format. For some reason it decides to organize it like that.

2022-07-30 00:41 UTC, d-loret commented on src/jsd_ild1900.c
> +                    JSD_ILD1900_SMR_MAP[config->model];
Discussed offline. In the code all units are in meters, including MR.

2022-07-30 00:47 UTC, d-loret commented
@alex-brinkman, I updated based on our findings when we tested in the lab. I am also excluding linearized and unlinearized distances from the state for simplicity's sake (I don't think we can get very helpful information from them).

2022-08-05 01:42 UTC, merged