Alex servo enable plus issue cleanup
nasa-jpl/jsd pull request #37
Opened 2022-09-22 21:34 UTC by alex-brinkman

* Exposes `servo_enabled` flag to public API (closes #35)
* Added printout to help with AC settings (closes #12)
* Exposes both `fault_code` and new `fault_enum` state to best describe fault types to downstream apps (closes #32)
* Precheck there is a valid position controller on the drive and emit helpful error messages (closes #19) 

Bump minor version

2022-09-24 02:58 UTC, d-loret requested changes
@alex-brinkman, thanks for updating the error portion.

 Please see my comments on the subindex of objec 0x6502 and on the new SDO timeout error behavior.

2022-09-24 02:58 UTC, d-loret commented on src/jsd_egd.c
> +        state->egd.new_async_sdo_timeout_error = true;
`state->num_async_sdo_requests` and `state->num_async_sdo_responses` are never reset. So after encountering the first SDO timeout, the driver would get an SDO timeout error every `JSD_EGD_ASYNC_SDO_TIMEOUT_SEC`. This is related to my other comment on halting when encountering this error.

It's tricky, we cannot simply reset those variables here because not all SDO requests in progress necessarily timed out (i.e. in future cycles we might receive their responses), and I think `num_async_sdo_requests` is written by the SDO thread.

2022-09-24 02:58 UTC, d-loret commented on src/jsd_egd.c
> +  //   cannot be used and the drive will through an error.
typo in "throw"

2022-09-24 02:58 UTC, d-loret commented on src/jsd_egd.c
> +  if (!jsd_sdo_get_param_blocking(ecx_context, slave_id, 0x6502, 18, JSD_SDO_DATA_U32,
Does it actually have a subindex different from 0? I couldn't find subindices for 0x6502 in the docs.

2022-09-26 17:29 UTC, alex-brinkman commented on src/jsd_egd.c
> +        state->egd.new_async_sdo_timeout_error = true;
* add API call to zero out requests and response counters (to be called by Fastcat::Reset)
* if responses > requests, responses = requests
*

2022-09-29 22:40 UTC, alex-brinkman commented
@d-loret I am going to close this branch without merge. I will open up a new branch and PR to close out the minor cleanup issues and add the servo_enabled flag. All error code changes will die in this PR.

2022-09-29 22:40 UTC, closed without merging