Alex sdo response mods
nasa-jpl/jsd pull request #44
Opened 2022-09-30 16:00 UTC by alex-brinkman

Address #43 
* Pass a user-provided request number to help applications keep track of individual requests
* Modify the response circular queues from one-per-device to a single SDO response queue
* No longer pop the response circular queues (leave that to the downstream application for more fine-grained control)

2022-10-07 02:34 UTC, d-loret reviewed
Looks good in general! I still need to look at how the errors are being handled in fastcat to piece together all the puzzle.

2022-10-07 02:34 UTC, d-loret commented on src/jsd_sdo.c
> +    memset(&req.data, 0, sizeof(req.data));
Can there be valid SDO writes without actual data to write?
If the answer is no, I think we should not send the request down the line in this case.

2022-10-07 02:34 UTC, d-loret commented on src/jsd_egd_pub.h
> + * to verify result and handle SDO-set failures.
Can you just add a note here for this specific function that `jsd_egd_set_gain_scheduling_index` may depend on the outcome of the request?

2022-10-07 02:34 UTC, d-loret commented on src/jsd_el3104.c
> +  // no-op
I wonder whether it is worth to keep the process functions for input devices like this one. These functions are not called at all.

2022-10-07 23:39 UTC, alex-brinkman commented on src/jsd_sdo_pub.h
> - * A most the background thread exchanges one device SDO request each cycle.
yes

2022-10-07 23:40 UTC, alex-brinkman commented on src/jsd_sdo.c
> +void jsd_sdo_push_async_request(jsd_t* self, jsd_sdo_req_t request)
sure, doesn't hurt.

2022-10-07 23:54 UTC, alex-brinkman commented on src/jsd_el3104.c
> +  // no-op
There is only one sdo response queue now so it's either all or nothing.

2022-10-07 23:57 UTC, alex-brinkman commented on src/jsd_sdo.c
> +    memset(&req.data, 0, sizeof(req.data));
Hmmn good catch!

This function just populates a struct as a  many-argument-to-struct conversion function, nothing more and cannot return failure through this retval (unless we want to `assert`... which causes other issues like loss of actuator positions....)

Since the `jsd_sdo_req_t` contains the actual SDO-write data, we cannot "catch" this fault in downstream. I will handle this by introducing another invalid type that is checked in downstream calls.

2022-10-08 00:22 UTC, alex-brinkman commented on src/jsd_sdo.c
> +    memset(&req.data, 0, sizeof(req.data));
Should be address in newer commit

2022-10-08 05:21 UTC, d-loret requested changes
A bug was introduced in the handling of the invalid write SDO. We need to check in the else clause it's not a read request.

2022-10-08 05:21 UTC, d-loret commented on src/jsd_sdo.c
> +  }else{
This makes read requests invalid.

2022-10-08 05:21 UTC, d-loret commented on src/jsd_sdo_pub.h
> - * A most the background thread exchanges one device SDO request each cycle.
So should we add that remark back to the comment?

2022-10-08 05:21 UTC, d-loret commented on src/jsd_el3104.c
> +  // no-op
Not sure I follow "it's either or nothing," but I personally think we should remove these processing functions. They are no-ops and they are not called.

2022-10-10 15:20 UTC, alex-brinkman commented on src/jsd_sdo.c
> +  }else{
I agree, good catch!

2022-10-10 15:21 UTC, merged

2022-10-24 22:13 UTC, d-loret reviewed
Revisiting these PRs.

2022-10-24 22:13 UTC, d-loret commented on src/jsd_el3104.c
> +  // no-op
@alex-brinkman, I think this point is unresolved. These process functions are no-ops and are never called. In my opinion they should be removed.

2022-10-25 16:04 UTC, alex-brinkman commented
Opened https://github.com/nasa-jpl/jsd/issues/51 to track the removal of these functions. This constitutes a Major version change FWIW since these are all public API functions.