Alex fault codes
nasa-jpl/jsd pull request #46
Opened 2022-10-03 22:34 UTC by alex-brinkman

Closing #44 first will shrink the size of this PR.

* closes #45 by introducing a thread-safe error circular queue, one for each device. 
* EGD state now includes both the JSD enum `fault_code` as well as the raw EMCY code `emcy_error_code`
* In EGD, slightly modifies how the FAULT state transitions back to OPERATION_ENABLED
* uses SOEM function to display all EMCY codes so nothing should be missed
* Tested on a DC brushed motor

2022-10-08 07:19 UTC, d-loret requested changes
This looks great, although I do have a few comments.

I am also having difficulties keeping track of the data exchange between threads. It would be very helpful for the review to have a diagram of the threads involved, their nature with respect to real-time guarantees (e.g. SDO thread is not real-time safe as currently written but I don't know if that is the desired behavior), the data structures used to interchange data between them, which thread pushes or pops those data structures and when in the thread that happens.
We this high level view I would be able to better provide feedback, and it would also reduce the chances of me overlooking something important. We could meet and draw this in paper.

2022-10-08 07:19 UTC, d-loret commented on src/jsd_egd.c
> +            set_controlword(self, slave_id,
I am a little lost here. Is the latching of the fault achieved by only resetting `state->pub.emcy_error_cod` and `state->pub.fault_code` at the start of the next enable operation?

What about other potential errors in the queue? We are just handling one.

2022-10-08 07:28 UTC, d-loret commented on src/jsd_sdo_pub.h
> +bool jsd_sdo_pop_response_queue(jsd_t* self, jsd_sdo_req_t* response);
One other important question: what is the intended plan on how applications call this function? For example, if I want to issue an SDO read from one of the Fastcat drivers for whatever reason, how can the driver obtain the response without popping responses not intended for it?

2022-10-10 15:38 UTC, alex-brinkman commented on src/jsd_error_cirq.c
> +    WARNING("Popping [%s] when empty", self->name);
It's not likely to print but your suggest does invite me to reconsider the pop function prototype. 
Right now, this is the right way to poll the queue:
```
     if(!jsd_error_cirq_is_empty(error_cirq)) {
        ec_errort error = jsd_error_cirq_pop(error_cirq);
        // do something
    }
```
Which has the downside of locking/unlocking the mutex twice for each check :/


Stay tuned for a minor API change that should make this both more abuse-proof and reduce the first redundant lock/unlock.

2022-10-10 15:43 UTC, alex-brinkman commented on src/jsd_error_cirq.c
> +  if (jsd_error_cirq_is_empty(self)) {
Any read or write of any field in the circular queue needs to be protected by mutex {`buffer`, `r`, `w`, `name`} for guaranteed data coherence. Getting fancy here is far more likely to trip us up plus any performance gain is unquantified (also this would be one of the last places I'd look for gains should it come to that!)

2022-10-10 15:51 UTC, alex-brinkman commented on src/jsd_error_cirq.c
> +static bool push_error(jsd_error_cirq_t* self, ec_errort error) {
I don't disagree with you but consider 2 things: 
1) Modern compilers are good at optimizing out these types of inefficiencies - how sure are you that it actually performs better? Premature optimization is the root of all evil so they say... ;)
2) At first glance, it's far more obvious to a dev that passing in a `ec_errort` by value is a read-only argument. 
if it's `ec_errort*` I now have to worry if that function will modify my data structure or perhaps return something meaningful through that argument (and it could even free it!) So for comprehension it may be better to pass by value for read-only arguments.

2022-10-10 15:52 UTC, alex-brinkman commented on src/jsd_sdo.c
> +    self->r++;
Ya, I only found it when I setup proper UTs for the stand-alone `jsd_error_cirq` "class"

2022-10-10 15:57 UTC, alex-brinkman commented on src/jsd_sdo.c
> +      pthread_cond_timedwait(&self->sdo_thread_cond, &self->jsd_sdo_req_cirq.mutex, &ts);
This is needed when 2 signals are raised quickly by the main process - If the SDO thread is already awake, signaling the SDO to wake does nothing. This could lead to state-machine "locking" if the main process is waiting for some result the SDO needs to handle, for example update the error cirq.

2022-10-10 15:59 UTC, alex-brinkman commented on src/jsd_sdo.c
> +        ecx_mbxreceive(&self->ecx_context, sid, &MbxIn, 0);
`0` is typically reserved for the master in SOEM, slaves start at `1`. I found that using `0` did not work in practice and instead it must be received by the slave id.

2022-10-10 16:15 UTC, alex-brinkman commented on src/jsd_egd.c
> +        state->new_reset = false;
Clearning/setting it in the place provide more expected state machine response.

When the drive is faulted, any request to reset is cleared - meaning the drive will stay in a latched-fault state until a new reset is commanded.

When a reset is commanded, we want the drive to transition to operation enabled - regardless of how many internal EGD statemachine transition are needed. 

Hope that explains it

2022-10-10 16:19 UTC, alex-brinkman commented on src/jsd_egd.c
> +        if(ectime_to_double(error.Time) > state->fault_time){
`state->fault_time` is only updated on a new FAULT state transition, here:

https://github.com/nasa-jpl/jsd/blob/0cc9c195c6014a0aa0809d4732aeba19c2a96705/src/jsd_egd.c#L1135

2022-10-10 16:33 UTC, alex-brinkman commented on src/jsd_sdo_pub.h
> +bool jsd_sdo_pop_response_queue(jsd_t* self, jsd_sdo_req_t* response);
It's intended the application pop this response queue until empty every iteration and handle them as desired. The application necessarily knows every async sdo command issued to each device!

2022-10-10 16:34 UTC, alex-brinkman commented on src/jsd_sdo_pub.h
> +bool jsd_sdo_pop_response_queue(jsd_t* self, jsd_sdo_req_t* response);
set GS index is a PDO operation (changing GS mode is an SDO operation - and therefore cannot have real-time guarantees)

2022-10-10 16:34 UTC, alex-brinkman commented on src/jsd_egd.c
> +      } else if(jsd_get_time_sec() > (1.0 + state->fault_time) &&
IIRC all EGD transitions to FAULT will raise an EMCY code.

2022-10-10 16:35 UTC, alex-brinkman commented on src/jsd_egd.c
> +      } else if(jsd_get_time_sec() > (1.0 + state->fault_time) &&
regardless, the result is that the EGD won't transition to Operation Enabled until the operator issues a reset.

2022-10-10 16:38 UTC, alex-brinkman commented on src/jsd_egd.c
> +            set_controlword(self, slave_id,
While were in the FAULT state, we will check the error_cirq for new errors (that occured after the transition to FAULT) Once we get a device error that occured after this time, we can stop checking and transition out of FAULT. 
Again, the state-machine will not transition all the way to Enabled, and will wait for a RESET command to go back to enabled.

2022-10-10 16:41 UTC, alex-brinkman commented on src/jsd_sdo.c
> +    jsd_sdo_req_t popped_res = queue_pop(sdo_queue);
I agree, in the interest of minimizing code change I left this implementation as is. When I introduced the `jsd_error_cirq` "class" I created a standalone .c/.h for it - it promoted testing and found bugs before they bit us too! 

I'm happy to pull this out in the same manner but didn't want to cause more headaches since there is already a ton of code change

2022-10-10 16:42 UTC, alex-brinkman commented on src/jsd_sdo.c
> +    jsd_sdo_req_t popped_res = queue_pop(sdo_queue);
captured here #47

2022-10-10 16:45 UTC, alex-brinkman commented on src/jsd_sdo.c
> +    memcpy(res, &popped_res, sizeof(popped_res));
I was concerned the copy operation for POD wouldn't work with the anonymous union contained within `jsd_sdo_req_t`.. let me dig...

2022-10-10 16:47 UTC, alex-brinkman commented on src/jsd_egd.c
> +      state->new_reset = false; // clear any potentially ongoing reset request
If faulted, the fastcat command queue is cleared after reading and before writing.
https://github.com/nasa-jpl/fastcat/blob/c3b71a9bedf2295bf019eb3e7a445dc5c08d65f9/src/manager.cc#L617

2022-10-10 16:55 UTC, alex-brinkman commented on src/jsd_egd.c
> +  return (double)t.sec + (double)(t.usec)*1.0e6;
Great catch!!!
I didn't observe this since I'm using the SOEM print function to format the EMCY code timestamp. This bug means that virtually any EMCY would have exceeded the fault time transition - not the biggest issue but glad to squash this one in review!

2022-10-10 18:52 UTC, alex-brinkman commented
@d-loret I'm going to re-test this on hardware - pending a successful checkout, I'll conclude this PR.

2022-10-14 18:00 UTC, merged

2022-10-26 03:52 UTC, d-loret commented on src/jsd_egd.c
> +        state->new_reset = false;
I see there is some subtlety here because the EGD state machine will not wait for a reset to exit the fault state (`JSD_EGD_STATE_MACHINE_STATE_FAULT`). The thing that gets latched is the error code variable.

See my other comment about `state->new_reset`: setting it to `false` only at the end of this function should still be correct.

2022-10-26 04:18 UTC, d-loret commented on src/jsd_egd.c
> +        if(ectime_to_double(error.Time) > state->fault_time){
So why not adding a time function that uses monotonic time (i.e. `clock_gettime`) and use that when dealing with `state->fault_time` since we are comparing it with SOEM's time?

The possibility of not pairing the right EMCY error with the fault because of a time discrepancy is there. Additionally, for measuring time lapses like in the timeout check for not receiving the error, we should be using monotonic clocks.

2022-10-26 04:18 UTC, d-loret commented on src/jsd_egd.c
> +      } else if(jsd_get_time_sec() > (1.0 + state->fault_time) &&
Just keep in mind that a reset only has an effect after you are out of `JSD_EGD_STATE_MACHINE_STATE_FAULT`, so you will have to wait for 1 second even if you send a reset before the wait ends.

2022-10-26 04:39 UTC, d-loret commented on src/jsd_egd.c
> +              state->pub.fault_code != JSD_EGD_FAULT_UNKNOWN)
There is an issue here. If we go into this if clause and set `state->pub.fault_code` to `JSD_EGD_FAULT_UNKNOWN`, and we get another fault while we are waiting in the SWITCHED_ON state, and the EMCY never arrives, we will be waiting for eternity because of the value of `state->pub.fault_code`.

2022-10-26 04:39 UTC, d-loret commented on src/jsd_sdo_pub.h
> +bool jsd_sdo_pop_response_queue(jsd_t* self, jsd_sdo_req_t* response);
For my first question I was thinking a scenario where, for example, during the configuration step of the driver, I need to read in some parameter via SDO before configuring some other value. In that case, how can I get the SDO response at the driver level?

2022-10-26 04:39 UTC, d-loret commented on src/jsd_sdo_pub.h
> +bool jsd_sdo_pop_response_queue(jsd_t* self, jsd_sdo_req_t* response);
For my second question, to avoid overflowing the response queues, do we need to empty the queue in fcat at every iteration?

2022-10-26 16:23 UTC, alex-brinkman commented
> For my first question I was thinking a scenario where, for example, during the configuration step of the driver, I need to read in some parameter via SDO before configuring some other value. In that case, how can I get the SDO response at the driver level?

Just use the blocking SDO read/write API calls littered throughout all the PO2SO callbacks.

For your other comments, let's start an issue so we can talk through the changes I made here in a more tractable way.

2022-10-26 16:28 UTC, alex-brinkman commented on src/jsd_error_cirq.h
> + * @param error_out the new error, NULL if queue was empty
fair point, I'll make a new issue to redress in future versions.