Elmo Platinum motor controller driver - cyclic synchronous position
nasa-jpl/jsd pull request #64
Opened 2022-12-15 05:18 UTC by d-loret

Initial implementation of the driver for the new Elmo Platinum motor controller drives. The initial implementation focuses on the cyclic synchronous position mode.

2023-03-09 22:32 UTC, alex-brinkman requested changes
Great work Daniel! I commend your efforts here.

I like the addition of the elmo common header and your judgement between what should be specific to Gold and Platinum devices. 

My eyes starting glossing over between `epd` and `egd` - do you think it might be worth doing a string replace to make these names more visually discernable?

Finally, can you update the README to include this device in the library?

I did not run these tests since you're the only one with the platinum hardware, assuming this is working well on hardware, feel free to merge once the requested changes are completel and bump the MAJOR release version.

2023-03-09 22:32 UTC, alex-brinkman commented on src/jsd_epd.c
> +}
Can you add a few unit tests for this lookup method since it's non-trivial? I wish these were easily computed like in the EGD case :/

2023-03-09 22:32 UTC, alex-brinkman commented on src/jsd_epd.c
> +  // 0x1608.
If it's working, rm this comment

2023-03-09 22:32 UTC, alex-brinkman commented on src/jsd_epd.c
> +  // TODO(dloret): Didn't we disable Complete Access somewhere else?
If it's working, rm this comment

2023-03-09 22:32 UTC, alex-brinkman commented on src/jsd_epd.c
> +  // 0x1A08.
If it's working, rm this comment

2023-03-09 22:32 UTC, alex-brinkman commented on src/jsd_epd.c
> +  // jsd_epd_lc_to_do must be checked before attempting to send the SDO.
Please do this before merge, as this will influence the API relating to TL commands!

2023-03-09 22:32 UTC, alex-brinkman commented on src/jsd_epd.c
> +void jsd_epd_process_state_machine(jsd_t* self, uint16_t slave_id) {
I've gotta trust you on this with hardware-in-loop testing

2023-03-09 22:54 UTC, d-loret commented
Some examples of the tests I did:

![platinum_prof_pos_debug](https://user-images.githubusercontent.com/99947029/224178578-d9e33dff-f463-4199-b552-fd18a1c32322.png)
![platinum_prof_vel_debug](https://user-images.githubusercontent.com/99947029/224178603-c20a2626-027a-43ea-80d2-89fb3a931f02.png)
![platinum_prof_torque_debug](https://user-images.githubusercontent.com/99947029/224178646-9f06902a-9081-46a1-9b0c-76e5dcd6f9b2.png)

2023-03-09 23:04 UTC, alex-brinkman commented
The command ACK they added to the platinum is a nice feature, it was awkward there was nothing like this in the prof pos command mode on the EGD

2023-03-16 05:28 UTC, d-loret commented on src/jsd_epd.c
> +}
I have added a unit test querying the currently used letter commands and the special case 0x0000.

2023-03-16 05:28 UTC, d-loret commented on src/jsd_epd.c
> +  // jsd_epd_lc_to_do must be checked before attempting to send the SDO.
I did test this, so I have removed the comment.

2023-03-16 05:36 UTC, d-loret commented
@alex-brinkman, I have addressed your comments.

About the naming of EGD and EPD, I would prefer if we keep them as they are right now. I personally like how clean the naming of functions, types, and especially enumeration labels end up.

2023-03-16 16:53 UTC, alex-brinkman approved these changes

2023-03-16 16:54 UTC, alex-brinkman commented
Fix that minor merge conflict and then you can merge and mint an updated release. Probably start a new minor release with this sizeable addition.

2023-03-16 17:16 UTC, merged