created github actions(#11) for building source code and testing it
nasa-jpl/jsd pull request #75
Opened 2023-05-03 08:15 UTC by japrozs

added github actions for CI – https://github.com/nasa-jpl/jsd/issues/11

2023-05-03 21:14 UTC, preston-rogers requested changes

2023-05-03 21:14 UTC, preston-rogers commented on .github/workflows/test.yaml
> +            - uses: solareenlo/42valgrind-action@v1.0.3
Also, just tried running this github action and it requires a file:

/bin/bash: line 0: .: filename argument required
.: usage: . filename [arguments]

![image](https://user-images.githubusercontent.com/128186734/236050780-1af31310-a4e5-41cc-8fc5-6ec581b72094.png)

2023-05-03 21:14 UTC, preston-rogers commented on .github/workflows/build.yaml
If you want to copy over these changes, I found that the build action will fail with the current code set-up. This commit fixes that:
https://github.com/japrozs/jsd/commit/4a440dacb9ec1ab141df2e7471c5545618580d07

2023-05-04 08:34 UTC, japrozs commented on .github/CODEOWNERS
> +*	@nasa-jpl
i changed the codeowner to `@nasa-jpl/nasa-jpl-ethercat-devs`

2023-05-04 08:36 UTC, japrozs commented on .github/workflows/test.yaml
> +            - uses: solareenlo/42valgrind-action@v1.0.3
i just swapped the valgrind plugin because i couldn't find a stable github action for valgrind. i changed the action to install valgrind using `apt-get` and then use it

2023-05-04 08:36 UTC, japrozs commented on .github/workflows/build.yaml
yeah, sure!

2023-06-09 17:30 UTC, alex-brinkman commented
@preston-rogers Is this ready for merge? It would be awesome to get the action setup and working

2023-06-15 19:38 UTC, japrozs commented
> Hey @japrozs, please let me know if you need further information. I will add the necessary changes to pass CI by EOD Thursday PST otherwise.

i think the PR is good to merge 👍🏼

2023-06-20 16:36 UTC, preston-rogers commented
Hello @japrozs. After testing your changes, the actions fail partly due to a variable unused warnings and because the chosen valgrind was failing on the ubuntu 22.04 runner. I made the necessary modifications in the following PR. Please merge this in and once that is done, I'm happy to merge this into the main JSD repo.
https://github.com/japrozs/jsd/pull/1

2023-06-20 22:25 UTC, preston-rogers commented
> > Hello @japrozs. After testing your changes, the actions fail partly due to a variable unused warnings and because the chosen valgrind was failing on the ubuntu 22.04 runner. I made the necessary modifications in the following PR. Please merge this in and once that is done, I'm happy to merge this into the main JSD repo. [japrozs#1](https://github.com/japrozs/jsd/pull/1)
> 
> yep, i merged the PR. thanks for fixing the issues 👍🏼

No problem! My fault, but could you make a new PR trying to merge the master branch of your forked repo into the master branch of nasa-jpl? Accidentally made the necessary changes on your master branch.

2023-06-21 11:38 UTC, japrozs commented
yeah; i’ll create a new PR with the changes

2023-06-21 18:58 UTC, closed without merging

2023-06-21 19:18 UTC, japrozs commented
> > > Hello @japrozs. After testing your changes, the actions fail partly due to a variable unused warnings and because the chosen valgrind was failing on the ubuntu 22.04 runner. I made the necessary modifications in the following PR. Please merge this in and once that is done, I'm happy to merge this into the main JSD repo. [japrozs#1](https://github.com/japrozs/jsd/pull/1)
> > 
> > 
> > yep, i merged the PR. thanks for fixing the issues 👍🏼
> 
> No problem! My fault, but could you make a new PR trying to merge the master branch of your forked repo into the master branch of nasa-jpl? Accidentally made the necessary changes on your master branch. After the new PR is created please delete this one.

@preston-rogers here you go – https://github.com/nasa-jpl/jsd/pull/91

2023-06-21 21:47 UTC, preston-rogers commented
Thank you Japroz 🙂
________________________________
From: Japroz Saini ***@***.***>
Sent: Wednesday, June 21, 2023 12:18 PM
To: nasa-jpl/jsd ***@***.***>
Cc: Rogers, Preston (US 347G) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [nasa-jpl/jsd] created github actions(#11) for building source code and testing it (PR #75)


Hello @japrozs<https://urldefense.us/v3/__https://github.com/japrozs__;!!PvBDto6Hs4WbVuu7!J3tvyhNJlUOQkyXnpzwstsdBD0nYKM7azq_X-vnF6SQGFcwPWVcYYxPd_Fq_30PeKeaUZHl6b3chv3hl6y2ySzqKZTIt$>. After testing your changes, the actions fail partly due to a variable unused warnings and because the chosen valgrind was failing on the ubuntu 22.04 runner. I made the necessary modifications in the following PR. Please merge this in and once that is done, I'm happy to merge this into the main JSD repo. japrozs#1<https://urldefense.us/v3/__https://github.com/japrozs/jsd/pull/1__;!!PvBDto6Hs4WbVuu7!J3tvyhNJlUOQkyXnpzwstsdBD0nYKM7azq_X-vnF6SQGFcwPWVcYYxPd_Fq_30PeKeaUZHl6b3chv3hl6y2ySyYzqjRv$>

yep, i merged the PR. thanks for fixing the issues 👍🏼

No problem! My fault, but could you make a new PR trying to merge the master branch of your forked repo into the master branch of nasa-jpl? Accidentally made the necessary changes on your master branch. After the new PR is created please delete this one.

@preston-rogers<https://urldefense.us/v3/__https://github.com/preston-rogers__;!!PvBDto6Hs4WbVuu7!J3tvyhNJlUOQkyXnpzwstsdBD0nYKM7azq_X-vnF6SQGFcwPWVcYYxPd_Fq_30PeKeaUZHl6b3chv3hl6y2yS81ghlFH$> here you go – #91<https://urldefense.us/v3/__https://github.com/nasa-jpl/jsd/pull/91__;!!PvBDto6Hs4WbVuu7!J3tvyhNJlUOQkyXnpzwstsdBD0nYKM7azq_X-vnF6SQGFcwPWVcYYxPd_Fq_30PeKeaUZHl6b3chv3hl6y2yS0sRvPnv$>

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https://github.com/nasa-jpl/jsd/pull/75*issuecomment-1601523182__;Iw!!PvBDto6Hs4WbVuu7!J3tvyhNJlUOQkyXnpzwstsdBD0nYKM7azq_X-vnF6SQGFcwPWVcYYxPd_Fq_30PeKeaUZHl6b3chv3hl6y2yS3O2kAAB$>, or unsubscribe<https://urldefense.us/v3/__https://github.com/notifications/unsubscribe-auth/A6R7S3X55N6NJAA35VVFKX3XMNCHVANCNFSM6AAAAAAXUB5BYY__;!!PvBDto6Hs4WbVuu7!J3tvyhNJlUOQkyXnpzwstsdBD0nYKM7azq_X-vnF6SQGFcwPWVcYYxPd_Fq_30PeKeaUZHl6b3chv3hl6y2yS4lgHWks$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>